In [1]:
import numpy as np
import pandas as pd

In [2]:
date=pd.read_csv('orders.csv')
time =pd.read_csv('messages.csv')

In [3]:
date.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [4]:
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [5]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [6]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

In [8]:
date.shape

(1000, 4)

In [9]:
time.shape

(1000, 2)

In [10]:
###working with the date

In [11]:
#Converting to datetime datatype
date['date']=pd.to_datetime(date['date'])

In [12]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

In [13]:
#Extract year

In [14]:
date['date_year']=date['date'].dt.year

In [15]:
date.sample

<bound method NDFrame.sample of           date  product_id  city_id  orders  date_year
0   2019-12-10        5628       25       3       2019
1   2018-08-15        3646       14     157       2018
2   2018-10-23        1859       25       1       2018
3   2019-08-17        7292       25       1       2019
4   2019-01-06        4344       25       3       2019
..         ...         ...      ...     ...        ...
995 2018-10-08         255       13       1       2018
996 2018-12-06        5521        7       1       2018
997 2019-05-07         487       26      14       2019
998 2019-03-03        1503       21       2       2019
999 2019-10-15        6371        7      22       2019

[1000 rows x 5 columns]>

In [16]:
#Extract Month

In [17]:
date['date_month_no']=date['date'].dt.month
date.head()

        date  product_id  city_id  orders  date_year  date_month_no
0 2019-12-10        5628       25       3       2019             12
1 2018-08-15        3646       14     157       2018              8
2 2018-10-23        1859       25       1       2018             10
3 2019-08-17        7292       25       1       2019              8
4 2019-01-06        4344       25       3       2019              1

In [18]:
date['date_month_name']=date['date'].dt.month_name()
date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name
0,2019-12-10,5628,25,3,2019,12,December
1,2018-08-15,3646,14,157,2018,8,August
2,2018-10-23,1859,25,1,2018,10,October
3,2019-08-17,7292,25,1,2019,8,August
4,2019-01-06,4344,25,3,2019,1,January

In [19]:
#Extract Days

In [20]:
date['date_day']=date['date'].dt.day
date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,date_day
0,2019-12-10,5628,25,3,2019,12,December,10
1,2018-08-15,3646,14,157,2018,8,August,15
2,2018-10-23,1859,25,1,2018,10,October,23
3,2019-08-17,7292,25,1,2019,8,August,17
4,2019-01-06,4344,25,3,2019,1,January,6

In [21]:
#Days of weeks

In [22]:
date['date_dow']=date['date'].dt.dayofweek
date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,date_day,date_dow
0,2019-12-10,5628,25,3,2019,12,December,10,1
1,2018-08-15,3646,14,157,2018,8,August,15,2
2,2018-10-23,1859,25,1,2018,10,October,23,1
3,2019-08-17,7292,25,1,2019,8,August,17,5
4,2019-01-06,4344,25,3,2019,1,January,6,6

In [23]:
date['date_dow_name']=date['date'].dt.day_name()
date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,date_month_name,date_day,date_dow,date_dow_name
0,2019-12-10,2019,12,December,10,1,Tuesday
1,2018-08-15,2018,8,August,15,2,Wednesday
2,2018-10-23,2018,10,October,23,1,Tuesday
3,2019-08-17,2019,8,August,17,5,Saturday
4,2019-01-06,2019,1,January,6,6,Sunday

In [24]:
#is weekend or not?

In [25]:
date['date_is_weekend']=np.where(date['date_dow_name'].isin(['Sunday','Saturday']),1,0)
date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend
0,2019-12-10,2019,12,December,10,1,Tuesday,0
1,2018-08-15,2018,8,August,15,2,Wednesday,0
2,2018-10-23,2018,10,October,23,1,Tuesday,0
3,2019-08-17,2019,8,August,17,5,Saturday,1
4,2019-01-06,2019,1,January,6,6,Sunday,1

In [26]:
#Extracting week of the year:

In [37]:
date['date_week']=date['date'].dt.isocalendar().week
date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend,semester,quarter,date_week
0,2019-12-10,2019,12,December,10,1,Tuesday,0,2,4,50
1,2018-08-15,2018,8,August,15,2,Wednesday,0,2,3,33
2,2018-10-23,2018,10,October,23,1,Tuesday,0,2,4,43
3,2019-08-17,2019,8,August,17,5,Saturday,1,2,3,33
4,2019-01-06,2019,1,January,6,6,Sunday,1,1,1,1

In [29]:
#Extracting Quater

In [34]:
date['quarter']=date['date'].dt.quarter
date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend,semester,quarter
0,2019-12-10,2019,12,December,10,1,Tuesday,0,2,4
1,2018-08-15,2018,8,August,15,2,Wednesday,0,2,3
2,2018-10-23,2018,10,October,23,1,Tuesday,0,2,4
3,2019-08-17,2019,8,August,17,5,Saturday,1,2,3
4,2019-01-06,2019,1,January,6,6,Sunday,1,1,1

In [35]:
#Extract Semesters

In [33]:
date['semester']=(date['date'].dt.month>6).astype(int)+1
date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend,semester
0,2019-12-10,2019,12,December,10,1,Tuesday,0,2
1,2018-08-15,2018,8,August,15,2,Wednesday,0,2
2,2018-10-23,2018,10,October,23,1,Tuesday,0,2
3,2019-08-17,2019,8,August,17,5,Saturday,1,2
4,2019-01-06,2019,1,January,6,6,Sunday,1,1

In [38]:
import datetime

In [39]:
today=datetime.datetime.today()
today

datetime.datetime(2026, 9, 30, 10, 28, 42, 62221)

In [40]:
today-date['date']

0     2486 days 10:28:42.062221
1     2968 days 10:28:42.062221
2     2899 days 10:28:42.062221
3     2601 days 10:28:42.062221
4     2824 days 10:28:42.062221
                 ...
995   2914 days 10:28:42.062221
996   2855 days 10:28:42.062221
997   2703 days 10:28:42.062221
998   2768 days 10:28:42.062221
999   2542 days 10:28:42.062221
Name: date, Length: 1000, dtype: timedelta64[ns]

In [41]:
(today-date['date']).dt.days

0      2486
1      2968
2      2899
3      2601
4      2824
       ...
995    2914
996    2855
997    2703
998    2768
999    2542
Name: date, Length: 1000, dtype: int64

In [42]:
#Month passed:

In [44]:
np.round((today-date['date'])/np.timedelta64(1,'D')/30.44,0)

0      82.0
1      98.0
2      95.0
3      85.0
4      93.0
       ...
995    96.0
996    94.0
997    89.0
998    91.0
999    84.0
Name: date, Length: 1000, dtype: float64

In [45]:
time['date']=pd.to_datetime(time['date'])

In [46]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
 1   msg     1000 non-null   object
dtypes: datetime64[ns](1), object(1)
memory usage: 15.8+ KB

In [48]:
time['hour']=time['date'].dt.hour
time['min']=time['date'].dt.minute
time['sec']=time['date'].dt.second
time.head()

,date,msg,hour,min,sec
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0

In [51]:
time['time']=time['date'].dt.time
time.head()

,date,msg,hour,min,sec,time
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0,00:50:00
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0,23:40:00
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0,00:21:00
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0,00:31:00
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0,23:11:00

In [50]:
today-time['date']

0     4672 days 09:38:42.062221
1     4536 days 10:48:42.062221
2     5022 days 10:07:42.062221
3     4324 days 09:57:42.062221
4     4721 days 11:17:42.062221
                 ...
995   5311 days 09:38:42.062221
996   4632 days 11:14:42.062221
997   5097 days 10:51:42.062221
998   5213 days 10:54:42.062221
999   4485 days 11:03:42.062221
Name: date, Length: 1000, dtype: timedelta64[ns]